<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pits_cookieconsent"
 *
 * Auto generated by Extension Builder 2018-05-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'PITS Cookie Consent',
    'description' => 'The most popular solution to the EU cookie law.
Rigged with TYPO3 codebase',
    'category' => 'plugin',
    'author' => 'Anu Bhuvanendran Nair',
    'author_email' => 'anu.bn@pitsolutions.com',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-9.0.0',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
